# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SRT_Creator.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QMainWindow,
    QProgressBar, QPushButton, QSizePolicy, QStatusBar,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(580, 626)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(300, 40, 261, 31))
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(20, 40, 101, 31))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(130, 510, 91, 31))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(20, 100, 321, 21))
        self.progressBar.setValue(0)
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(240, 510, 91, 31))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(350, 510, 91, 31))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(460, 510, 101, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 91, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(300, 20, 91, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 80, 91, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 130, 91, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 490, 61, 16))
        self.comboBox_2 = QComboBox(self.centralwidget)
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(160, 40, 101, 31))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 20, 51, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 430, 131, 16))
        self.pushButton_1 = QPushButton(self.centralwidget)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setGeometry(QRect(20, 450, 121, 31))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(160, 450, 121, 31))
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(300, 450, 121, 31))
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(440, 450, 121, 31))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(350, 100, 81, 21))
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(470, 100, 91, 21))
        self.pushButton_10 = QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(130, 560, 91, 31))
        self.pushButton_11 = QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(240, 560, 91, 31))
        self.pushButton_12 = QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(350, 560, 91, 31))
        self.pushButton_13 = QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(460, 560, 101, 31))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 510, 81, 31))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 560, 81, 31))
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(20, 150, 541, 271))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \uc120\ud0dd", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"base", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"large-v2", None))

        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\ud55c\uae00", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\uc601\uc5b4", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\uc77c\ubcf8\uc5b4", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\uc911\uad6d\uc5b4", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"1. \ubaa8\ub378 \uc120\ud0dd", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"3. \ud30c\uc77c \uc785\ub825", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"4. \uc9c4\ud589 \uc0c1\ud669", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"5. \uc790\ub9c9", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"7. \ubc88\uc5ed", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"\uc790\ub3d9", None))

        self.label_6.setText(QCoreApplication.translate("MainWindow", u"2. \uc5b8\uc5b4", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"6. \uc790\ub9c9 \uc2f1\ud06c \uc870\uc808", None))
        self.pushButton_1.setText(QCoreApplication.translate("MainWindow", u"0.1\ucd08 \ube60\ub974\uac8c", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"0.1\ucd08 \ub290\ub9ac\uac8c", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"1\ucd08 \ube60\ub974\uac8c", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"1\ucd08 \ub290\ub9ac\uac8c", None))
        self.label_8.setText("")
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\ud55c\uae00", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"\uc601\uc5b4", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"\uc77c\ubcf8\uc5b4", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"\uc911\uad6d\uc5b4", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\uad6c\uae00 \ubc88\uc5ed", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"DeepL \ubc88\uc5ed", None))
    # retranslateUi

